name: Add PR to Project

on:
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add PR to GitHub Project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectNumber = 1;  // Replace with your project number
            const columnName = 'Pull Requests';  // Replace with your column name

            const pr = context.payload.pull_request;

            const { data: projects } = await github.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const project = projects.find(p => p.number === projectNumber);

            if (!project) {
              throw new Error(`Project ${projectNumber} not found`);
            }

            const { data: columns } = await github.projects.listColumns({
              project_id: project.id,
            });

            const column = columns.find(column => column.name === columnName);

            if (!column) {
              throw new Error(`Column ${columnName} not found`);
            }

            await github.projects.createCard({
              column_id: column.id,
              content_id: pr.id,
              content_type: 'PullRequest',
            });
